// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package database_permission

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.CatalogID, b.ko.Spec.CatalogID) {
		delta.Add("Spec.CatalogID", a.ko.Spec.CatalogID, b.ko.Spec.CatalogID)
	} else if a.ko.Spec.CatalogID != nil && b.ko.Spec.CatalogID != nil {
		if *a.ko.Spec.CatalogID != *b.ko.Spec.CatalogID {
			delta.Add("Spec.CatalogID", a.ko.Spec.CatalogID, b.ko.Spec.CatalogID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Condition, b.ko.Spec.Condition) {
		delta.Add("Spec.Condition", a.ko.Spec.Condition, b.ko.Spec.Condition)
	} else if a.ko.Spec.Condition != nil && b.ko.Spec.Condition != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Condition.Expression, b.ko.Spec.Condition.Expression) {
			delta.Add("Spec.Condition.Expression", a.ko.Spec.Condition.Expression, b.ko.Spec.Condition.Expression)
		} else if a.ko.Spec.Condition.Expression != nil && b.ko.Spec.Condition.Expression != nil {
			if *a.ko.Spec.Condition.Expression != *b.ko.Spec.Condition.Expression {
				delta.Add("Spec.Condition.Expression", a.ko.Spec.Condition.Expression, b.ko.Spec.Condition.Expression)
			}
		}
	}
	if len(a.ko.Spec.Permissions) != len(b.ko.Spec.Permissions) {
		delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
	} else if len(a.ko.Spec.Permissions) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.Permissions, b.ko.Spec.Permissions) {
			delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
		}
	}
	if len(a.ko.Spec.PermissionsWithGrantOption) != len(b.ko.Spec.PermissionsWithGrantOption) {
		delta.Add("Spec.PermissionsWithGrantOption", a.ko.Spec.PermissionsWithGrantOption, b.ko.Spec.PermissionsWithGrantOption)
	} else if len(a.ko.Spec.PermissionsWithGrantOption) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.PermissionsWithGrantOption, b.ko.Spec.PermissionsWithGrantOption) {
			delta.Add("Spec.PermissionsWithGrantOption", a.ko.Spec.PermissionsWithGrantOption, b.ko.Spec.PermissionsWithGrantOption)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Principal, b.ko.Spec.Principal) {
		delta.Add("Spec.Principal", a.ko.Spec.Principal, b.ko.Spec.Principal)
	} else if a.ko.Spec.Principal != nil && b.ko.Spec.Principal != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Principal.DataLakePrincipalIdentifier, b.ko.Spec.Principal.DataLakePrincipalIdentifier) {
			delta.Add("Spec.Principal.DataLakePrincipalIdentifier", a.ko.Spec.Principal.DataLakePrincipalIdentifier, b.ko.Spec.Principal.DataLakePrincipalIdentifier)
		} else if a.ko.Spec.Principal.DataLakePrincipalIdentifier != nil && b.ko.Spec.Principal.DataLakePrincipalIdentifier != nil {
			if *a.ko.Spec.Principal.DataLakePrincipalIdentifier != *b.ko.Spec.Principal.DataLakePrincipalIdentifier {
				delta.Add("Spec.Principal.DataLakePrincipalIdentifier", a.ko.Spec.Principal.DataLakePrincipalIdentifier, b.ko.Spec.Principal.DataLakePrincipalIdentifier)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Resource, b.ko.Spec.Resource) {
		delta.Add("Spec.Resource", a.ko.Spec.Resource, b.ko.Spec.Resource)
	} else if a.ko.Spec.Resource != nil && b.ko.Spec.Resource != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Resource.Database, b.ko.Spec.Resource.Database) {
			delta.Add("Spec.Resource.Database", a.ko.Spec.Resource.Database, b.ko.Spec.Resource.Database)
		} else if a.ko.Spec.Resource.Database != nil && b.ko.Spec.Resource.Database != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Resource.Database.CatalogID, b.ko.Spec.Resource.Database.CatalogID) {
				delta.Add("Spec.Resource.Database.CatalogID", a.ko.Spec.Resource.Database.CatalogID, b.ko.Spec.Resource.Database.CatalogID)
			} else if a.ko.Spec.Resource.Database.CatalogID != nil && b.ko.Spec.Resource.Database.CatalogID != nil {
				if *a.ko.Spec.Resource.Database.CatalogID != *b.ko.Spec.Resource.Database.CatalogID {
					delta.Add("Spec.Resource.Database.CatalogID", a.ko.Spec.Resource.Database.CatalogID, b.ko.Spec.Resource.Database.CatalogID)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Resource.Database.Name, b.ko.Spec.Resource.Database.Name) {
				delta.Add("Spec.Resource.Database.Name", a.ko.Spec.Resource.Database.Name, b.ko.Spec.Resource.Database.Name)
			} else if a.ko.Spec.Resource.Database.Name != nil && b.ko.Spec.Resource.Database.Name != nil {
				if *a.ko.Spec.Resource.Database.Name != *b.ko.Spec.Resource.Database.Name {
					delta.Add("Spec.Resource.Database.Name", a.ko.Spec.Resource.Database.Name, b.ko.Spec.Resource.Database.Name)
				}
			}
		}
	}

	return delta
}
