// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package database_permission

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/lakeformation"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/lakeformation/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/lakeformation-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.DatabasePermission{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	if r.ko.Spec.Resource != nil && r.ko.Spec.Resource.Database != nil {
		input.Resource = &svcsdktypes.Resource{
			Database: &svcsdktypes.DatabaseResource{
				CatalogId: r.ko.Spec.Resource.Database.CatalogID,
				Name:      r.ko.Spec.Resource.Database.Name,
			},
		}
	}
	if r.ko.Spec.Principal != nil {
		input.Principal = &svcsdktypes.DataLakePrincipal{
			DataLakePrincipalIdentifier: r.ko.Spec.Principal.DataLakePrincipalIdentifier,
		}
	}

	var resp *svcsdk.ListPermissionsOutput
	resp, err = rm.sdkapi.ListPermissions(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "ListPermissions", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.PrincipalResourcePermissions {
		if elem.Condition != nil {
			f1 := &svcapitypes.Condition{}
			if elem.Condition.Expression != nil {
				f1.Expression = elem.Condition.Expression
			}
			ko.Spec.Condition = f1
		} else {
			ko.Spec.Condition = nil
		}
		if elem.Permissions != nil {
			f4 := []*string{}
			for _, f4iter := range elem.Permissions {
				var f4elem *string
				f4elem = aws.String(string(f4iter))
				f4 = append(f4, f4elem)
			}
			ko.Spec.Permissions = f4
		} else {
			ko.Spec.Permissions = nil
		}
		if elem.PermissionsWithGrantOption != nil {
			f5 := []*string{}
			for _, f5iter := range elem.PermissionsWithGrantOption {
				var f5elem *string
				f5elem = aws.String(string(f5iter))
				f5 = append(f5, f5elem)
			}
			ko.Spec.PermissionsWithGrantOption = f5
		} else {
			ko.Spec.PermissionsWithGrantOption = nil
		}
		if elem.Principal != nil {
			f6 := &svcapitypes.DataLakePrincipal{}
			if elem.Principal.DataLakePrincipalIdentifier != nil {
				f6.DataLakePrincipalIdentifier = elem.Principal.DataLakePrincipalIdentifier
			}
			ko.Spec.Principal = f6
		} else {
			ko.Spec.Principal = nil
		}
		if elem.Resource != nil {
			f7 := &svcapitypes.Resource{}
			if elem.Resource.Database != nil {
				f7f0 := &svcapitypes.DatabaseResource{}
				if elem.Resource.Database.CatalogId != nil {
					f7f0.CatalogID = elem.Resource.Database.CatalogId
				}
				if elem.Resource.Database.Name != nil {
					f7f0.Name = elem.Resource.Database.Name
				}
				f7.Database = f7f0
			}
			ko.Spec.Resource = f7
		} else {
			ko.Spec.Resource = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	// The ListPermissions API can return more than the single grant this CR
	// manages: entries derived from LF-Tag policies or RAM resource shares show
	// up as "effective" permissions alongside explicitly granted ones, and the
	// server-side Resource/Principal filter above narrows but does not
	// guarantee an exact match. Re-scan the raw response here rather than
	// trusting whichever entry the generated code above happened to pick first.
	matched := false
	for _, elem := range resp.PrincipalResourcePermissions {
		if elem.AdditionalDetails != nil && len(elem.AdditionalDetails.ResourceShare) > 0 {
			// Share-derived, not a grant this CR made.
			continue
		}
		if elem.Principal == nil || elem.Principal.DataLakePrincipalIdentifier == nil {
			continue
		}
		if r.ko.Spec.Principal == nil || r.ko.Spec.Principal.DataLakePrincipalIdentifier == nil {
			continue
		}
		if *elem.Principal.DataLakePrincipalIdentifier != *r.ko.Spec.Principal.DataLakePrincipalIdentifier {
			continue
		}

		permissions := make([]*string, 0, len(elem.Permissions))
		for _, p := range elem.Permissions {
			permissions = append(permissions, aws.String(string(p)))
		}
		ko.Spec.Permissions = permissions

		permissionsWithGrantOption := make([]*string, 0, len(elem.PermissionsWithGrantOption))
		for _, p := range elem.PermissionsWithGrantOption {
			permissionsWithGrantOption = append(permissionsWithGrantOption, aws.String(string(p)))
		}
		ko.Spec.PermissionsWithGrantOption = permissionsWithGrantOption

		matched = true
		break
	}
	if !matched {
		return nil, ackerr.NotFound
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return false
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.ListPermissionsInput, error) {
	res := &svcsdk.ListPermissionsInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GrantPermissionsOutput
	_ = resp
	resp, err = rm.sdkapi.GrantPermissions(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "GrantPermissions", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.GrantPermissionsInput, error) {
	res := &svcsdk.GrantPermissionsInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}
	if r.ko.Spec.Condition != nil {
		f1 := &svcsdktypes.Condition{}
		if r.ko.Spec.Condition.Expression != nil {
			f1.Expression = r.ko.Spec.Condition.Expression
		}
		res.Condition = f1
	}
	if r.ko.Spec.Permissions != nil {
		f2 := []svcsdktypes.Permission{}
		for _, f2iter := range r.ko.Spec.Permissions {
			var f2elem string
			f2elem = string(*f2iter)
			f2 = append(f2, svcsdktypes.Permission(f2elem))
		}
		res.Permissions = f2
	}
	if r.ko.Spec.PermissionsWithGrantOption != nil {
		f3 := []svcsdktypes.Permission{}
		for _, f3iter := range r.ko.Spec.PermissionsWithGrantOption {
			var f3elem string
			f3elem = string(*f3iter)
			f3 = append(f3, svcsdktypes.Permission(f3elem))
		}
		res.PermissionsWithGrantOption = f3
	}
	if r.ko.Spec.Principal != nil {
		f4 := &svcsdktypes.DataLakePrincipal{}
		if r.ko.Spec.Principal.DataLakePrincipalIdentifier != nil {
			f4.DataLakePrincipalIdentifier = r.ko.Spec.Principal.DataLakePrincipalIdentifier
		}
		res.Principal = f4
	}
	if r.ko.Spec.Resource != nil {
		f5 := &svcsdktypes.Resource{}
		if r.ko.Spec.Resource.Database != nil {
			f5f0 := &svcsdktypes.DatabaseResource{}
			if r.ko.Spec.Resource.Database.CatalogID != nil {
				f5f0.CatalogId = r.ko.Spec.Resource.Database.CatalogID
			}
			if r.ko.Spec.Resource.Database.Name != nil {
				f5f0.Name = r.ko.Spec.Resource.Database.Name
			}
			f5.Database = f5f0
		}
		res.Resource = f5
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return nil, ackerr.NewTerminalError(ackerr.NotImplemented)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.RevokePermissionsOutput
	_ = resp
	resp, err = rm.sdkapi.RevokePermissions(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "RevokePermissions", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.RevokePermissionsInput, error) {
	res := &svcsdk.RevokePermissionsInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}
	if r.ko.Spec.Condition != nil {
		f1 := &svcsdktypes.Condition{}
		if r.ko.Spec.Condition.Expression != nil {
			f1.Expression = r.ko.Spec.Condition.Expression
		}
		res.Condition = f1
	}
	if r.ko.Spec.Permissions != nil {
		f2 := []svcsdktypes.Permission{}
		for _, f2iter := range r.ko.Spec.Permissions {
			var f2elem string
			f2elem = string(*f2iter)
			f2 = append(f2, svcsdktypes.Permission(f2elem))
		}
		res.Permissions = f2
	}
	if r.ko.Spec.PermissionsWithGrantOption != nil {
		f3 := []svcsdktypes.Permission{}
		for _, f3iter := range r.ko.Spec.PermissionsWithGrantOption {
			var f3elem string
			f3elem = string(*f3iter)
			f3 = append(f3, svcsdktypes.Permission(f3elem))
		}
		res.PermissionsWithGrantOption = f3
	}
	if r.ko.Spec.Principal != nil {
		f4 := &svcsdktypes.DataLakePrincipal{}
		if r.ko.Spec.Principal.DataLakePrincipalIdentifier != nil {
			f4.DataLakePrincipalIdentifier = r.ko.Spec.Principal.DataLakePrincipalIdentifier
		}
		res.Principal = f4
	}
	if r.ko.Spec.Resource != nil {
		f5 := &svcsdktypes.Resource{}
		if r.ko.Spec.Resource.Database != nil {
			f5f0 := &svcsdktypes.DatabaseResource{}
			if r.ko.Spec.Resource.Database.CatalogID != nil {
				f5f0.CatalogId = r.ko.Spec.Resource.Database.CatalogID
			}
			if r.ko.Spec.Resource.Database.Name != nil {
				f5f0.Name = r.ko.Spec.Resource.Database.Name
			}
			f5.Database = f5f0
		}
		res.Resource = f5
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.DatabasePermission,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
