// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ApplicationStatus string

const (
	ApplicationStatus_DISABLED ApplicationStatus = "DISABLED"
	ApplicationStatus_ENABLED  ApplicationStatus = "ENABLED"
)

type ComparisonOperator string

const (
	ComparisonOperator_BEGINS_WITH  ComparisonOperator = "BEGINS_WITH"
	ComparisonOperator_BETWEEN      ComparisonOperator = "BETWEEN"
	ComparisonOperator_CONTAINS     ComparisonOperator = "CONTAINS"
	ComparisonOperator_EQ           ComparisonOperator = "EQ"
	ComparisonOperator_GE           ComparisonOperator = "GE"
	ComparisonOperator_GT           ComparisonOperator = "GT"
	ComparisonOperator_IN           ComparisonOperator = "IN"
	ComparisonOperator_LE           ComparisonOperator = "LE"
	ComparisonOperator_LT           ComparisonOperator = "LT"
	ComparisonOperator_NE           ComparisonOperator = "NE"
	ComparisonOperator_NOT_CONTAINS ComparisonOperator = "NOT_CONTAINS"
)

type CredentialsScope string

const (
	CredentialsScope_READ      CredentialsScope = "READ"
	CredentialsScope_READWRITE CredentialsScope = "READWRITE"
)

type DataLakeResourceType string

const (
	DataLakeResourceType_CATALOG                 DataLakeResourceType = "CATALOG"
	DataLakeResourceType_DATABASE                DataLakeResourceType = "DATABASE"
	DataLakeResourceType_DATA_LOCATION           DataLakeResourceType = "DATA_LOCATION"
	DataLakeResourceType_LF_NAMED_TAG_EXPRESSION DataLakeResourceType = "LF_NAMED_TAG_EXPRESSION"
	DataLakeResourceType_LF_TAG                  DataLakeResourceType = "LF_TAG"
	DataLakeResourceType_LF_TAG_POLICY           DataLakeResourceType = "LF_TAG_POLICY"
	DataLakeResourceType_LF_TAG_POLICY_DATABASE  DataLakeResourceType = "LF_TAG_POLICY_DATABASE"
	DataLakeResourceType_LF_TAG_POLICY_TABLE     DataLakeResourceType = "LF_TAG_POLICY_TABLE"
	DataLakeResourceType_TABLE                   DataLakeResourceType = "TABLE"
)

type EnableStatus string

const (
	EnableStatus_DISABLED EnableStatus = "DISABLED"
	EnableStatus_ENABLED  EnableStatus = "ENABLED"
)

type FieldNameString string

const (
	FieldNameString_LAST_MODIFIED FieldNameString = "LAST_MODIFIED"
	FieldNameString_RESOURCE_ARN  FieldNameString = "RESOURCE_ARN"
	FieldNameString_ROLE_ARN      FieldNameString = "ROLE_ARN"
)

type OptimizerType string

const (
	OptimizerType_ALL                OptimizerType = "ALL"
	OptimizerType_COMPACTION         OptimizerType = "COMPACTION"
	OptimizerType_GARBAGE_COLLECTION OptimizerType = "GARBAGE_COLLECTION"
)

type Permission string

const (
	Permission_ALL                          Permission = "ALL"
	Permission_ALTER                        Permission = "ALTER"
	Permission_ASSOCIATE                    Permission = "ASSOCIATE"
	Permission_CREATE_CATALOG               Permission = "CREATE_CATALOG"
	Permission_CREATE_DATABASE              Permission = "CREATE_DATABASE"
	Permission_CREATE_LF_TAG                Permission = "CREATE_LF_TAG"
	Permission_CREATE_LF_TAG_EXPRESSION     Permission = "CREATE_LF_TAG_EXPRESSION"
	Permission_CREATE_TABLE                 Permission = "CREATE_TABLE"
	Permission_DATA_LOCATION_ACCESS         Permission = "DATA_LOCATION_ACCESS"
	Permission_DELETE                       Permission = "DELETE"
	Permission_DESCRIBE                     Permission = "DESCRIBE"
	Permission_DROP                         Permission = "DROP"
	Permission_GRANT_WITH_LF_TAG_EXPRESSION Permission = "GRANT_WITH_LF_TAG_EXPRESSION"
	Permission_INSERT                       Permission = "INSERT"
	Permission_SELECT                       Permission = "SELECT"
	Permission_SUPER_USER                   Permission = "SUPER_USER"
)

type PermissionType string

const (
	PermissionType_CELL_FILTER_PERMISSION PermissionType = "CELL_FILTER_PERMISSION"
	PermissionType_COLUMN_PERMISSION      PermissionType = "COLUMN_PERMISSION"
	PermissionType_NESTED_CELL_PERMISSION PermissionType = "NESTED_CELL_PERMISSION"
	PermissionType_NESTED_PERMISSION      PermissionType = "NESTED_PERMISSION"
)

type QueryStateString string

const (
	QueryStateString_ERROR               QueryStateString = "ERROR"
	QueryStateString_EXPIRED             QueryStateString = "EXPIRED"
	QueryStateString_FINISHED            QueryStateString = "FINISHED"
	QueryStateString_PENDING             QueryStateString = "PENDING"
	QueryStateString_WORKUNITS_AVAILABLE QueryStateString = "WORKUNITS_AVAILABLE"
)

type ResourceShareType string

const (
	ResourceShareType_ALL     ResourceShareType = "ALL"
	ResourceShareType_FOREIGN ResourceShareType = "FOREIGN"
)

type ResourceType string

const (
	ResourceType_DATABASE ResourceType = "DATABASE"
	ResourceType_TABLE    ResourceType = "TABLE"
)

type ServiceAuthorization string

const (
	ServiceAuthorization_DISABLED ServiceAuthorization = "DISABLED"
	ServiceAuthorization_ENABLED  ServiceAuthorization = "ENABLED"
)

type TransactionStatus string

const (
	TransactionStatus_ABORTED            TransactionStatus = "ABORTED"
	TransactionStatus_ACTIVE             TransactionStatus = "ACTIVE"
	TransactionStatus_COMMITTED          TransactionStatus = "COMMITTED"
	TransactionStatus_COMMIT_IN_PROGRESS TransactionStatus = "COMMIT_IN_PROGRESS"
)

type TransactionStatusFilter string

const (
	TransactionStatusFilter_ABORTED   TransactionStatusFilter = "ABORTED"
	TransactionStatusFilter_ACTIVE    TransactionStatusFilter = "ACTIVE"
	TransactionStatusFilter_ALL       TransactionStatusFilter = "ALL"
	TransactionStatusFilter_COMMITTED TransactionStatusFilter = "COMMITTED"
	TransactionStatusFilter_COMPLETED TransactionStatusFilter = "COMPLETED"
)

type TransactionType string

const (
	TransactionType_READ_AND_WRITE TransactionType = "READ_AND_WRITE"
	TransactionType_READ_ONLY      TransactionType = "READ_ONLY"
)

type VerificationStatus string

const (
	VerificationStatus_NOT_VERIFIED        VerificationStatus = "NOT_VERIFIED"
	VerificationStatus_VERIFICATION_FAILED VerificationStatus = "VERIFICATION_FAILED"
	VerificationStatus_VERIFIED            VerificationStatus = "VERIFIED"
)
